version: "3.8"

services:
  pd_symlinker:
    container_name: pd_symlinker
    image: stranulax/pd_symlinker:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t   
    environment:
      TZ: "your_timezone" # e.g., "America/New_York"
    volumes:
      # Location of zurg folder to monitor
      - /path/to/src_dir:/data/torrents
      # Location for sorted items
      - /path/to/dest_dir:/data/sorted
      # Location for Plex_Debrid catalog.csv
      - /path/to/catalog:/catalog
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN     
    security_opt:
      - apparmor:unconfined    
      - no-new-privileges
    entrypoint: ["/entrypoint.sh"]
    command: ["python", "pd_symlinker.py"]  # Replace with your actual command
