version: "3.8"

services:
  pd_symlinker:
    container_name: pd_symlinker
    image: stranulax/pd_symlinker:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t   
    environment:
      TZ: "America/New_York" # e.g., "America/New_York"
      TOP_FOLDER: "/folder/above/zurg_mnt"
      SRC_DIR: "/top_folder/zurg_mnt/torrents"
      DEST_DIR: "/top_folder/sorted"
    volumes:
      # Location for Plex_Debrid catalog.csv
      - ${CATALOG_PATH}:/catalog
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN     
    security_opt:
      - apparmor:unconfined    
      - no-new-privileges
    entrypoint: ["/entrypoint.sh"]
    command: ["python", "pd_symlinker.py"]  # Replace with your actual command
